[files]
extend-exclude = [
    ".git/",
    ".github/",
    "__MACOSX/",
    ".DS_Store",
    "node_modules/",
    "dist/",
    "apis/",
    "benchmarks/merge/src/index.ts",
    "*.tsbuildinfo",
    "*.log",
    "pnpm-debug.log*",
]
