packages:
    - ./packages/*
    - ./plugins/*
    - ./tests/*
    - ./tests/plugins/*
    - ./examples/*
    - ./templates/*
    - ./benchmarks/*

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    "@swc/core": true
    core-js: true
    esbuild: true
    sharp: true

catalogs:
    dep:
        es-toolkit: ^1.40.0
        fdir: ^6.5.0
        ts-vista: ~0.2.3
        # postcss
        postcss-flexbugs-fixes: ^5.0.0
        postcss-load-config: ^6.0.0
        postcss-preset-env: ^11.3.0
        # oxc
        oxc-parser: ~0.132.0
        oxc-minify: ~0.132.0
        rolldown: ^1.0.0
        # tsdown
        "@tsdown/css": ~0.22.2
        tsdown: ~0.22.0
        # vite
        vitest: ^4.1.8
        vite-tsconfig-paths: ^6.1.0
        # react
        "@types/react": ^19.2.16
        "@types/react-dom": ^19.2.0
        react: ^19.2.7
        react-dom: ^19.2.7
        # next
        next: 16.2.7
    dev:
        # unplugin
        webpack: 5.76.0
        "@rspack/core": 1.5.0
        rollup: 4.40.0
        rolldown: 1.0.0
        vite: 7.0.0
        # rsbuild
        "@rsbuild/core": 1.5.0
        # next
        next: 16.0.0
        # postcss
        postcss: 8.5.0
    peer:
        # unplugin
        webpack: ^5.76.0
        "@rspack/core": ^1.5.0 || ^2.0.0
        rollup: ^4.40.0
        rolldown: ^1.0.0
        vite: ^7.0.0 || ^8.0.0
        # rsbuild
        "@rsbuild/core": ^1.5.0 || ^2.0.0
        # next
        next: ^15.0.0 || ^16.0.0
        # postcss
        postcss: ^8.5.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    # config
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    # core
    - "ts-vista"
