import type { Metadata } from "next";
import type { NextFontWithVariable } from "next/dist/compiled/@next/font";
import type * as React from "react";

import { Geist, Geist_Mono } from "next/font/google";

import "#/styles/index.css";

const geistSans: NextFontWithVariable = Geist({
    variable: "--font-geist-sans",
    subsets: [
        "latin",
    ],
});

const geistMono: NextFontWithVariable = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: [
        "latin",
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>): React.JSX.Element => {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                {children}
            </body>
        </html>
    );
};
